### ISSUE TITLE
Ja valo lage nai : 

### ISSUE THREAD

**Issue by SwapnilBasher** [pz1971/Online-Judge-Solutions#1]
eto yaa boro description ke porte jabe ha read-me te !
read-me choto kor ; bullet list use kor 
like these : https://www.google.com/search?q=bullet+list&client=firefox-b-d&sxsrf=ACYBGNRpzNvKdU3Who6HiLbsNa2g_X4Emg:1579332202590&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiQrKv3zoznAhUFILcAHZErAzoQ_AUoAXoECBMQAw&biw=1280&bih=644#imgrc=u7uVYGQKA7FIYM:

anyway .net framework pari na ; sikhais !
markdown use paris ?

**Comment by pz1971** [comment]
readme boro hoye gese? 😮
tui likhe de, choto kore ekta.

.net/markdown ami o pari na :3 

ar egula ki bullet list na?

![image](https://user-images.githubusercontent.com/42247008/72884304-1d72aa80-3d30-11ea-8bdd-dc34ae98eb68.png)
